services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trading_platform'
      - 'POSTGRES_USER=trading_user'
      - 'POSTGRES_PASSWORD=trading_password'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
