"""
Backtest Results ARIMA Analyzer - MAIN ORCHESTRATOR
===================================================

File: crypto_trading_model/arima/backtest_arima_analyzer.py

This module applies ARIMA analysis to backtest portfolio returns according to Model Formula:

1. Load backtest results (e.g., backtest_results_neutral.xlsx)
2. Extract Daily_Return column (Phase 2 portfolio returns)
3. Apply ARIMA stationarity testing and optimization
4. Generate portfolio return forecasts for enhanced trading decisions

Usage:
    analyzer = BacktestArimaAnalyzer(logger)
    arima_result = analyzer.analyze_backtest_results("backtest_results_neutral.xlsx")
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from ..custom_logging.logger import CustomLogger
from .data_stationarity import DataStationarity, PreparedData
from .arima_optimizer import ArimaOptimizer, ArimaResult

class BacktestArimaError(Exception):
    """Exception raised for backtest ARIMA analysis errors."""
    pass

class BacktestArimaAnalyzer:
    """
    Analyzes backtest portfolio returns using ARIMA for enhanced trading decisions.
    
    This class implements the Model Formula ARIMA workflow specifically for 
    portfolio returns generated by your Phase 1 & Phase 2 optimization.
    """
    
    def __init__(self, logger: CustomLogger):
        """
        Initialize the BacktestArimaAnalyzer.
        
        Args:
            logger: Custom logger instance
        """
        self.logger = logger
        self.stationarity_tester = DataStationarity(logger)
        self.arima_optimizer = ArimaOptimizer(logger)
    
    def analyze_backtest_results(self, backtest_file_path: str, 
                               risk_profile: str = "neutral") -> Dict[str, Any]:
        """
        Analyze backtest results for ARIMA patterns in portfolio returns.
        
        Args:
            backtest_file_path: Path to backtest results file (Excel or CSV)
            risk_profile: Risk profile analyzed ("neutral", "averse", "lover")
            
        Returns:
            Dictionary with comprehensive ARIMA analysis results
            
        Raises:
            BacktestArimaError: If analysis fails
        """
        try:
            self.logger.info(f"Starting ARIMA analysis of backtest results: {backtest_file_path}")
            self.logger.info(f"Risk profile: {risk_profile}")
            
            # Load backtest results
            backtest_data = self._load_backtest_results(backtest_file_path)
            
            # Extract and validate portfolio returns
            portfolio_returns = self._extract_portfolio_returns(backtest_data)
            
            # Perform ARIMA analysis
            arima_analysis = self._perform_portfolio_arima_analysis(portfolio_returns, risk_profile)
            
            # Generate trading insights
            trading_insights = self._generate_trading_insights(arima_analysis, portfolio_returns)
            
            # Create comprehensive results
            results = {
                'risk_profile': risk_profile,
                'backtest_file': backtest_file_path,
                'portfolio_statistics': self._calculate_portfolio_statistics(portfolio_returns),
                'arima_analysis': arima_analysis,
                'trading_insights': trading_insights,
                'forecast_ready': arima_analysis['arima_result'].forecast_ready,
                'next_steps': self._determine_next_steps(arima_analysis)
            }
            
            self.logger.info("Backtest ARIMA analysis completed successfully")
            # At the end of your existing analyze_backtest_results() method:

            if results['forecast_ready']:
                from .arima_master_data_exporter import ArimaMasterDataExporter

                exporter = ArimaMasterDataExporter(self.logger)
                master_data_path = f"arima_master_data_{risk_profile}.json"

                # Export master data
                exporter.export_arima_master_data(
                    arima_result=results['arima_analysis']['arima_result'],
                    prepared_data=results['arima_analysis']['prepared_data'],
                    portfolio_returns=portfolio_returns,
                    output_path=master_data_path
                )

                results['master_data_path'] = master_data_path
            return results
            
        except Exception as e:
            error_msg = f"Backtest ARIMA analysis failed: {e}"
            self.logger.error(error_msg)
            raise BacktestArimaError(error_msg)
    
    def _load_backtest_results(self, file_path: str) -> pd.DataFrame:
        """Load backtest results from Excel or CSV file."""
        try:
            file_path = Path(file_path)
            
            if not file_path.exists():
                raise BacktestArimaError(f"Backtest results file not found: {file_path}")
            
            # Load based on file extension
            if file_path.suffix.lower() in ['.xlsx', '.xls']:
                data = pd.read_excel(file_path, sheet_name='Backtest Results')
                self.logger.info(f"Loaded Excel backtest results: {len(data)} rows")
            elif file_path.suffix.lower() == '.csv':
                data = pd.read_csv(file_path)
                self.logger.info(f"Loaded CSV backtest results: {len(data)} rows")
            else:
                raise BacktestArimaError(f"Unsupported file format: {file_path.suffix}")
            
            # Validate required columns
            required_columns = ['Timestamp', 'Daily_Return', 'Portfolio_Value', 'Strategy']
            missing_columns = [col for col in required_columns if col not in data.columns]
            if missing_columns:
                raise BacktestArimaError(f"Missing required columns in backtest results: {missing_columns}")
            
            self.logger.info(f"Backtest data validation passed: {len(data)} observations")
            return data
            
        except Exception as e:
            raise BacktestArimaError(f"Failed to load backtest results: {e}")
    
    def _extract_portfolio_returns(self, backtest_data: pd.DataFrame) -> pd.Series:
        """
        Extract and validate portfolio returns from backtest results.
        
        Args:
            backtest_data: Loaded backtest results
            
        Returns:
            Clean portfolio returns series ready for ARIMA analysis
        """
        try:
            # Extract Daily_Return column (Phase 2 portfolio returns)
            portfolio_returns = backtest_data['Daily_Return'].copy()
            
            # Convert timestamp to datetime if needed
            if 'Timestamp' in backtest_data.columns:
                timestamps = pd.to_datetime(backtest_data['Timestamp'])
                portfolio_returns.index = timestamps
                portfolio_returns.name = 'Portfolio_Daily_Return'
            
            # Remove any invalid values
            original_length = len(portfolio_returns)
            portfolio_returns = portfolio_returns.dropna()
            
            # Remove infinite values
            portfolio_returns = portfolio_returns[np.isfinite(portfolio_returns)]
            
            # Log data cleaning results
            cleaned_length = len(portfolio_returns)
            if cleaned_length < original_length:
                removed_count = original_length - cleaned_length
                self.logger.warning(f"Removed {removed_count} invalid portfolio return observations")
            
            # Validate sufficient data for ARIMA
            if cleaned_length < 30:
                raise BacktestArimaError(f"Insufficient portfolio return data for ARIMA: {cleaned_length} observations")
            
            # Log portfolio return statistics
            self.logger.info(f"Portfolio returns extracted: {cleaned_length} observations")
            self.logger.info(f"Portfolio return statistics:")
            self.logger.info(f"  Mean: {portfolio_returns.mean():.6f}")
            self.logger.info(f"  Std: {portfolio_returns.std():.6f}")
            self.logger.info(f"  Min: {portfolio_returns.min():.6f}")
            self.logger.info(f"  Max: {portfolio_returns.max():.6f}")
            
            return portfolio_returns
            
        except Exception as e:
            raise BacktestArimaError(f"Failed to extract portfolio returns: {e}")
    
    def _perform_portfolio_arima_analysis(self, portfolio_returns: pd.Series, 
                                        risk_profile: str) -> Dict[str, Any]:
        """
        Perform complete ARIMA analysis on portfolio returns.
        
        Args:
            portfolio_returns: Clean portfolio return series
            risk_profile: Risk profile being analyzed
            
        Returns:
            Dictionary with complete ARIMA analysis results
        """
        try:
            self.logger.info("=== Starting Portfolio Returns ARIMA Analysis ===")
            
            # Step 1: Prepare data (stationarity testing + preparation)
            self.logger.info("Step 1: Testing stationarity and preparing portfolio returns...")
            prepared_data = self.stationarity_tester.prepare_data(portfolio_returns)
            
            self.logger.info("Portfolio Return Stationarity Results:")
            self.logger.info(f"  - Original stationarity: {'YES' if prepared_data.stationarity_result.is_stationary else 'NO'}")
            self.logger.info(f"  - Differencing applied: {'YES' if prepared_data.is_differenced else 'NO'}")
            self.logger.info(f"  - ADF p-value: {prepared_data.stationarity_result.adf_pvalue:.6f}")
            self.logger.info(f"  - KPSS p-value: {prepared_data.stationarity_result.kpss_pvalue:.6f}")
            
            # Step 2: ARIMA parameter optimization
            self.logger.info("Step 2: Finding optimal ARIMA parameters for portfolio returns...")
            arima_result = self.arima_optimizer.find_optimal_arima(prepared_data)
            
            self.logger.info("Portfolio Return ARIMA Results:")
            self.logger.info(f"  - Optimal model: ARIMA{arima_result.best_order}")
            self.logger.info(f"  - Best AIC: {arima_result.best_aic:.4f}")
            self.logger.info(f"  - Significant coefficients: {len(arima_result.significant_coefficients)}")
            self.logger.info(f"  - Forecast ready: {arima_result.forecast_ready}")
            
            if arima_result.significant_coefficients:
                self.logger.info("  - Significant coefficients:")
                for name, value in arima_result.significant_coefficients.items():
                    self.logger.info(f"    {name}: {value:.8f}")
            
            return {
                'prepared_data': prepared_data,
                'arima_result': arima_result,
                'analysis_summary': {
                    'is_stationary': prepared_data.stationarity_result.is_stationary,
                    'differencing_applied': prepared_data.is_differenced,
                    'optimal_order': arima_result.best_order,
                    'best_aic': arima_result.best_aic,
                    'num_significant_coefficients': len(arima_result.significant_coefficients),
                    'forecast_ready': arima_result.forecast_ready
                }
            }
            
        except Exception as e:
            raise BacktestArimaError(f"Portfolio ARIMA analysis failed: {e}")
    
    def _calculate_portfolio_statistics(self, portfolio_returns: pd.Series) -> Dict[str, float]:
        """Calculate comprehensive portfolio statistics."""
        try:
            stats = {
                'total_observations': len(portfolio_returns),
                'mean_daily_return': portfolio_returns.mean(),
                'daily_volatility': portfolio_returns.std(),
                'annualized_return': portfolio_returns.mean() * 252,
                'annualized_volatility': portfolio_returns.std() * np.sqrt(252),
                'min_daily_return': portfolio_returns.min(),
                'max_daily_return': portfolio_returns.max(),
                'skewness': portfolio_returns.skew(),
                'kurtosis': portfolio_returns.kurtosis(),
                'positive_days': (portfolio_returns > 0).sum(),
                'negative_days': (portfolio_returns < 0).sum(),
                'zero_days': (portfolio_returns == 0).sum()
            }
            
            # Calculate Sharpe ratio
            if stats['annualized_volatility'] > 0:
                risk_free_rate = 0.04  # 4% annual - you can adjust this
                stats['sharpe_ratio'] = (stats['annualized_return'] - risk_free_rate) / stats['annualized_volatility']
            else:
                stats['sharpe_ratio'] = float('inf')
            
            # Win rate
            if stats['total_observations'] > 0:
                stats['win_rate'] = stats['positive_days'] / stats['total_observations']
            else:
                stats['win_rate'] = 0.0
            
            return stats
            
        except Exception as e:
            self.logger.error(f"Failed to calculate portfolio statistics: {e}")
            return {}
    
    def _generate_trading_insights(self, arima_analysis: Dict, portfolio_returns: pd.Series) -> Dict[str, Any]:
        """Generate actionable trading insights from ARIMA analysis."""
        insights = {
            'arima_insights': [],
            'risk_insights': [],
            'performance_insights': [],
            'integration_recommendations': []
        }
        
        try:
            arima_result = arima_analysis['arima_result']
            prepared_data = arima_analysis['prepared_data']
            
            # ARIMA-specific insights
            if arima_result.forecast_ready:
                insights['arima_insights'].extend([
                    f"✅ Portfolio returns show predictable patterns: ARIMA{arima_result.best_order}",
                    f"✅ {len(arima_result.significant_coefficients)} significant coefficients found",
                    "🎯 OPPORTUNITY: Portfolio return forecasting is viable"
                ])
                
                # Analyze model order for insights
                p, d, q = arima_result.best_order
                if p > 0:
                    insights['arima_insights'].append(f"📈 Autoregressive component (p={p}): Past returns influence future returns")
                if d > 0:
                    insights['arima_insights'].append(f"📊 Differencing (d={d}): Returns have trending behavior")
                if q > 0:
                    insights['arima_insights'].append(f"🔄 Moving average component (q={q}): Past shocks influence current returns")
                    
            else:
                insights['arima_insights'].extend([
                    "⚠️ Portfolio returns appear to follow random walk",
                    "⚠️ No significant ARIMA patterns detected",
                    "💡 Consider: Market efficiency suggests good strategy randomness"
                ])
            
            # Integration recommendations
            if arima_result.forecast_ready:
                insights['integration_recommendations'].extend([
                    "1. Implement portfolio return forecasting using significant coefficients",
                    "2. Use forecasts to adjust position sizing dynamically",
                    "3. Enhance Model Formula decision logic with return predictions",
                    "4. Consider forecast confidence intervals for risk management",
                    "5. Backtest enhanced model with ARIMA forecasting integration"
                ])
            else:
                insights['integration_recommendations'].extend([
                    "1. Current strategy appears optimally random (market efficient)",
                    "2. Focus on improving Phase 1 & Phase 2 optimization rather than forecasting",
                    "3. Consider applying ARIMA to individual asset returns instead",
                    "4. Monitor for regime changes that might create predictable patterns",
                    "5. Use ARIMA for risk management rather than return prediction"
                ])
            
        except Exception as e:
            self.logger.error(f"Failed to generate trading insights: {e}")
            insights['error'] = str(e)
        
        return insights
    
    def _determine_next_steps(self, arima_analysis: Dict) -> List[str]:
        """Determine recommended next steps based on ARIMA analysis."""
        next_steps = []
        
        try:
            arima_result = arima_analysis['arima_result']
            
            if arima_result.forecast_ready:
                next_steps.extend([
                    "🎯 PRIORITY: Implement Model Formula Step 5 (Forecasting Logic)",
                    "🔧 Integrate ARIMA forecasts with your backtester.py",
                    "📊 Create forecast-enhanced strategy selection",
                    "🧪 Backtest enhanced model vs current model",
                    "📈 Monitor forecast accuracy and model stability"
                ])
            else:
                next_steps.extend([
                    "📊 Analyze why no significant patterns were found",
                    "🔄 Try different ARIMA parameter ranges",
                    "💡 Consider GARCH models for volatility forecasting",
                    "🎯 Apply ARIMA to individual asset returns",
                    "✅ Current random strategy may already be optimal"
                ])
            
        except Exception as e:
            next_steps.append(f"⚠️ Error determining next steps: {e}")
        
        return next_steps

    def save_analysis_results(self, analysis_results: Dict, output_dir: str = "arima_analysis_results"):
        """Save comprehensive ARIMA analysis results to files."""
        try:
            output_path = Path(output_dir)
            output_path.mkdir(exist_ok=True)
            
            risk_profile = analysis_results.get('risk_profile', 'unknown')
            
            # Save detailed ARIMA analysis
            with open(output_path / f"arima_analysis_{risk_profile}.txt", "w") as f:
                f.write(f"ARIMA Analysis Results - {risk_profile.title()} Profile\n")
                f.write("=" * 60 + "\n\n")
                
                # Portfolio statistics
                f.write("Portfolio Statistics:\n")
                f.write("-" * 20 + "\n")
                stats = analysis_results.get('portfolio_statistics', {})
                for key, value in stats.items():
                    if isinstance(value, float):
                        f.write(f"{key}: {value:.6f}\n")
                    else:
                        f.write(f"{key}: {value}\n")
                
                f.write("\n")
                
                # ARIMA results
                if 'arima_analysis' in analysis_results:
                    arima_summary = analysis_results['arima_analysis']['analysis_summary']
                    f.write("ARIMA Analysis Summary:\n")
                    f.write("-" * 25 + "\n")
                    f.write(f"Optimal Order: ARIMA{arima_summary['optimal_order']}\n")
                    f.write(f"Best AIC: {arima_summary['best_aic']:.4f}\n")
                    f.write(f"Significant Coefficients: {arima_summary['num_significant_coefficients']}\n")
                    f.write(f"Forecast Ready: {arima_summary['forecast_ready']}\n")
                    f.write(f"Stationarity: {arima_summary['is_stationary']}\n")
                    f.write(f"Differencing Applied: {arima_summary['differencing_applied']}\n")
            
            self.logger.info(f"ARIMA analysis results saved to: {output_path}")
            
        except Exception as e:
            self.logger.error(f"Failed to save analysis results: {e}")